spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/moviebookingdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       ddl-auto: update
     show-sql: true

server:
  port: 8081
jwt:
   secret: mysecretkeymysecretkeymysecretkey12
   expiration: 3600000

